<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class TaskTest extends TestCase
{
    use DatabaseMigrations;

    protected $task;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->task = factory('App\Task')->create();
    }

    /** @test */
    function a_task_can_make_a_string_path()
    {
        $task = create('App\Task');

        $this->assertEquals(
            "/tasks/{$task->channel->slug}/{$task->id}", $task->path()
        );
    }

    /** @test */
    public function a_task_has_replies()
    {
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $this->task->posts);
    }

    /** @test */
    function a_task_has_a_creator()
    {
        $this->assertInstanceOf('App\User', $this->task->creator);
    }

    /** @test */
    function a_task_can_add_a_comment()
    {
        $this->task->addComment([
           'comments'   => 'Foobar',
            'user_id'   => 1
        ]);

        $this->assertCount(1, $this->task->posts);
    }

    /** @test */
    function a_task_belongs_to_a_channel()
    {
        $task = create('App\Task');

        $this->assertInstanceOf('App\Channel', $task->channel);
    }
}
